# Generated by Django 3.1.5 on 2021-01-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210114_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.URLField()),
                ('usuario', models.CharField(max_length=200)),
                ('testimonio', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dni', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPersonas', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('Dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario')),
                ('numeroHabitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.habitacion')),
            ],
        ),
    ]
