# Generated by Django 3.1.5 on 2021-01-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_reserva_testimonio_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numeroHabitacion',
            field=models.CharField(max_length=4),
        ),
    ]
