# Generated by Django 3.1.5 on 2021-01-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210117_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='contra',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
